layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 5
  exclude:
    forks: true
    projects:
    # - repo-name
     - Leetcode
     - Hackerank
     - Velda-Portfolio
     - veldakarimi.github.io
     - GADS-Mobile_Web_Specialist-
     
   
      

social_media:
  # behance: your_username
  # dribbble: your_username
  
  hackerrank: https://www.hackerrank.com/veldakiara 
  twitter: https://twitter.com/VeldaKiara
  medium: https://medium.com/@veldakarimi
  linkedin: https://www.linkedin.com/in/veldakiara/
  dev.to: https://dev.to/veldakiara 
  wordpress: https://veldakarimi.wordpress.com/

  # youtube: your_username

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: Django
    web_url: https://github.com/topics/django
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/django/django.png
  
  - name: React
    web_url: https://github.com/topics/react
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/react/react.png

  - name: Tensorflow
    web_url: https://github.com/topics/tensorflow
    image_url: https://raw.githubusercontent.com/github/explore/424902f9441eeb28663ad3f45e25398ac3445c79/topics/tensorflow/tensorflow.png
